---
# Installs magical cloud things

- name: Copy devmode.ps1
  win_copy:
    src: files/devmode.ps1
    dest: "{{ temp_dir }}"

- name: Execute devmode.ps1
  win_shell: powershell -ExecutionPolicy Unrestricted -File "{{ temp_dir }}devmode.ps1"

- name: Install WSL 2 msi package
  ansible.windows.win_package:
    path: https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
    state: present

- name: Set default WSL to WSL 2
  win_shell: wsl --set-default-version 2

- name: Reboot since required
  win_reboot:
      reboot_timeout_sec: 3600
      connect_timeout_sec: 3600
      shutdown_timeout_sec: 3600

- name: Install the latest and greatest container tools
  win_chocolatey:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-for-windows
    - docker-compose
    - minikube

- name: Install the latest version of Google Cloud SDK
  win_chocolatey:
    name: gcloudsdk
    state: latest

# - name: Install the latest and greatest HashiCorp utilities
#   win_chocolatey:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - vagrant
#     - packer
#     - terraform
#     - vault
