---
- name: Provisions Windows 10 Environment
  hosts: windows
  vars:
    ansible_python_interpreter: /usr/bin/python3
#  strategy: debug
#  ignore_errors: True
#  become: yes
#  become_method: runas
#  become_user: Administrator

  roles:
    - initialize
#    - office        # Installing office manually for 2019 version
    - libraries
    - tools
    - editors
#    - browsers      # No additional browsers needed at this time
    - cloud
    - finalize
