---
# Finalize setup

# - name: Install the latest NVIDIA driver
#   win_chocolatey:
#     name: geforce-game-ready-driver
#     state: latest
#   when: NVIDIA_GPU == true

- name: Reboot system
  win_reboot:
      reboot_timeout_sec: 3600
      connect_timeout_sec: 3600
      shutdown_timeout_sec: 3600
